### ISSUE TITLE
Possible leak cause by opening two sessions at once

### ISSUE THREAD

**Issue by mamoniot** [zerotier/zssp#33]
https://github.com/zerotier/zssp/blob/fb2b0aa2af439a99cae74546b4a19e8827f8feb1/performance/src/application.rs#L314

 The current protocol is Alice sends Bob a ratchet fingerprint, and then they both know to use the corresponding ratchet key for crypto. After a round of key exchange they then delete the old ratchet key and fingerprint, and replace them with a newly derived set. The replacement is performed atomically by the function `save_ratchet_state` of the `ApplicationLayer` trait linked above.

Let say Alice explicitly breaks the protocol by opening two sessions at the same time with Bob, using ratchet fingerprint "A".
It is possible for Bob to complete the key exchange on one of these sessions, derive new ratchet fingerprint "B", and then call `save_ratchet_state` with a `RatchetUpdate` that specifies to add "B" and delete "A" atomically. This call occurs in zeta.rs:808: https://github.com/zerotier/zssp/blob/fb2b0aa2af439a99cae74546b4a19e8827f8feb1/performance/src/zeta.rs#L882
Bob then may complete the key exchange for the second session, correctly drop the first session since it is redundant, derive new ratchet fingerprint "C", and then call `save_ratchet_state` with a `RatchetUpdate` that specifies to add "C" and delete "A" atomically. Because the first session was dropped, no future call to `save_ratchet_state` will be passed a `RatchetUpdate`  that specifies to delete "B". This means, depending on how the user implemented `save_ratchet_state`, "B" may just have been permanently leaked. Furthermore, if "B" is left dangling in Bob's database, it could cause undefined behavior in a user's application when it appears unexpectedly in database queries. If "B" is used by Bob to open a future session, it will have the effect of "rewinding" the post-compromise security to the point in time that "B" was created. This cannot be allowed if "B" is several days old.

There are a number of alternative behaviors Bob could exhibit when encountering this scenario. 
1. It would be correct and secure for Bob to refuse to open a second session with Alice as soon as they see that fingerprint "A" was reused. 
2. It would be correct and secure for Bob's database to "garbage collect" dangling fingerprint "B", and leave "C" as the only recognized ratchet fingerprint.
3. It would be correct and secure for Bob to require that `save_ratchet_state` returns an error, and rollback any database changes, if fingerprint "A" is not successfully deleted. This effectively means that both sessions with Alice will be closed, and "B" will be the only fingerprint in Bob's database.
4. It would be correct and secure for Bob to require that `save_ratchet_state` delete all ratchet fingerprints which are not specified in fields `state1` and `state2` of `RatchetUpdate`, regardless of whether `RatchetUpdate` says to delete them. So when Bob calls `save_ratchet_state` for the second time to add "C" to the database, Bob will also delete "B" from the database, even though `RatchetUpdate` does not explicitly say to delete "B".
5. It would be correct and secure for Bob to track that "A" has been reused by two different sessions, and then when the second call to `save_ratchet_state` is made, pass it a corrected `RatchetUpdate` that specifies to add "C" and delete "B" (instead of add "C" and delete "A").

We ought to choose one of these behaviors, and make it an explicit protocol requirement of ZSSP. Options 2, 3, and 4 make the semantics of `save_ratchet_state` more complicated to implement, and are thus breaking changes. Options 1 and 5 can be non-breaking changes, but are both complicated to implement and test, since they require caching database queries in hashtables. If there are other options I have not listed I would love to hear them, none of these options stick out to me as particularly "good".

**Comment by mamoniot** [comment]
In the absence of feedback I would lean towards option 4 being the least bad option, since it is moderately easy to implement for most database back-ends, and has predictable behavior.

**Comment by rcoder** [comment]
This is a great writeup; thanks!

My initial take would be that "adding `B` and deleting `A`" should indeed be atomic and durable such that any subsequent attempt to derive a new key from `A` would fail immediately.

If I've read the numbered options correctly, that would imply at least adopting option #1, with #3 a more strict (and arguably safer) approach. 

Assuming the session can be reestablished from initial key exchange I'd be inclined to go straight to #3, so any sessions which attempted to reuse an existing, "claimed" base key were immediately dropped. That being said, I don't actually know what the performance or reliability implications of that aggressive invalidation might be.

**Comment by mamoniot** [comment]
Whether or not the session can be re-established entirely depends upon how Alice ended up in a state where they attempted to open two sessions at once. In option #3, the "B" fingerprint will be the only one usable to re-establish a session. One of the two sessions Alice opened will have derived "B", so if Alice does not corrupt or overwrite "B", then Alice will be able to re-establish a session.
So if Alice is two VMs that are using two copies of the same virtual disk, only the VM which derived "B" will be able to re-establish connection.
It is also always possible for Alice and Bob to downgrade their ratchet to all zeros. This undermines post-compromise security but it does allow Alice and Bob to connect regardless of how Alice corrupted their ratchet.

#3 using SQLite should has minimal performance implications. For other back-ends I am not sure. Reliability is a bigger question mark. In normal usage ZSSP should already maintain synchronization with the database such that deletions always succeed. So I believe #3 does not impact reliability. There may be edge cases however that I have not thought of.
